name: Build and Push to ECR

on:
  push:
    branches:
      - development

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY_APP: 345852704676.dkr.ecr.us-east-1.amazonaws.com/webapp
      ECR_REPO_NAME_APP: webapp
      IMAGE_NAME_APP: webappimage
      
      ECR_REGISTRY_SQL: 345852704676.dkr.ecr.us-east-1.amazonaws.com/mysql
      ECR_REPO_NAME_SQL: mysql
      IMAGE_NAME_SQL: sqlimage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Docker image for App
        run: |
          docker build -t $ECR_REGISTRY_APP/$ECR_REPO_NAME_APP/$IMAGE_NAME_APP:$GITHUB_SHA .

      - name: Authenticate Docker to ECR for App
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_APP

      - name: Push Docker image to ECR for App
        run: |
          docker push $ECR_REGISTRY_APP/$ECR_REPO_NAME_APP/$IMAGE_NAME_APP:$GITHUB_SHA

      - name: Build Docker image for SQL
        run: |
          docker build -t $ECR_REGISTRY_SQL/$ECR_REPO_NAME_SQL/$IMAGE_NAME_SQL:$GITHUB_SHA .

      - name: Authenticate Docker to ECR for SQL
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_SQL

      - name: Push Docker image to ECR for SQL
        run: |
          docker push $ECR_REGISTRY_SQL/$ECR_REPO_NAME_SQL/$IMAGE_NAME_SQL:$GITHUB_SHA
